// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinUint64(x, y uint64) uint64 {
	if x < y {
		return x
	}
	return y
}

func MaxUint64(x, y uint64) uint64 {
	if x > y {
		return x
	}
	return y
}

func AbsUint64(x uint64) uint64 {
	if x < 0 {
		return -x
	}
	return x
}
