// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinInt64(x, y int64) int64 {
	if x < y {
		return x
	}
	return y
}

func MaxInt64(x, y int64) int64 {
	if x > y {
		return x
	}
	return y
}

func AbsInt64(x int64) int64 {
	if x < 0 {
		return -x
	}
	return x
}
