// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinFloat64(x, y float64) float64 {
	if x < y {
		return x
	}
	return y
}

func MaxFloat64(x, y float64) float64 {
	if x > y {
		return x
	}
	return y
}

func AbsFloat64(x float64) float64 {
	if x < 0 {
		return -x
	}
	return x
}
