// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinFloat32(x, y float32) float32 {
	if x < y {
		return x
	}
	return y
}

func MaxFloat32(x, y float32) float32 {
	if x > y {
		return x
	}
	return y
}

func AbsFloat32(x float32) float32 {
	if x < 0 {
		return -x
	}
	return x
}
