// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinInt8(x, y int8) int8 {
	if x < y {
		return x
	}
	return y
}

func MaxInt8(x, y int8) int8 {
	if x > y {
		return x
	}
	return y
}

func AbsInt8(x int8) int8 {
	if x < 0 {
		return -x
	}
	return x
}
