// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinInt16(x, y int16) int16 {
	if x < y {
		return x
	}
	return y
}

func MaxInt16(x, y int16) int16 {
	if x > y {
		return x
	}
	return y
}

func AbsInt16(x int16) int16 {
	if x < 0 {
		return -x
	}
	return x
}
