// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package maths

func MinUint32(x, y uint32) uint32 {
	if x < y {
		return x
	}
	return y
}

func MaxUint32(x, y uint32) uint32 {
	if x > y {
		return x
	}
	return y
}

func AbsUint32(x uint32) uint32 {
	if x < 0 {
		return -x
	}
	return x
}
