// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package set

type Uint16s struct {
	backing map[uint16]struct{}
}

func NewUint16s(initialElements ...uint16) *Uint16s {
	set := new(Uint16s)
	for _, x := range initialElements {
		set.Add(x)
	}
	return set
}

func (set *Uint16s) Add(x uint16) {
	if set.backing == nil {
		set.backing = make(map[uint16]struct{})
	}
	set.backing[x] = struct{}{}
}

func (set *Uint16s) Remove(x uint16) {
	delete(set.backing, x)
}

func (set *Uint16s) Contains(x uint16) bool {
	_, ok := set.backing[x]
	return ok
}

func (set *Uint16s) Comprises(vals ...uint16) bool {
	if set.Count() != len(vals) {
		return false
	}
	for _, v := range vals {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

func (set *Uint16s) Count() int {
	return len(set.backing)
}

func (set *Uint16s) Elements() []uint16 {
	elm := make([]uint16, 0, set.Count())
	for x, _ := range set.backing {
		elm = append(elm, x)
	}
	return elm
}

func (set *Uint16s) Clear() {
	for x, _ := range set.backing {
		set.Remove(x)
	}
}

func (set *Uint16s) Clone() *Uint16s {
	result := NewUint16s()
	for x, _ := range set.backing {
		result.Add(x)
	}
	return result
}

// ------------------------------------------------------------

func (a *Uint16s) Union(b *Uint16s) *Uint16s {
	result := a.Clone()
	for x, _ := range b.backing {
		result.Add(x)
	}
	return result
}

func (a *Uint16s) Intersection(b *Uint16s) *Uint16s {
	result := NewUint16s()

	smaller, larger := a, b
	if a.Count() > b.Count() {
		smaller, larger = b, a
	}

	for x, _ := range smaller.backing {
		if larger.Contains(x) {
			result.Add(x)
		}
	}
	return result
}

func (a *Uint16s) Difference(b *Uint16s) *Uint16s {
	result := a.Union(b)

	smaller, larger := a, b
	if a.Count() > b.Count() {
		smaller, larger = b, a
	}

	for x, _ := range smaller.backing {
		if larger.Contains(x) {
			result.Remove(x)
		}
	}
	return result
}

// Subtraction is non-commutative: a-b is different to b-a.
func (a *Uint16s) Subtract(b *Uint16s) *Uint16s {
	result := a.Clone()
	for x, _ := range b.backing {
		result.Remove(x)
	}
	return result
}
