// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package set

type Int64s struct {
	backing map[int64]struct{}
}

func NewInt64s(initialElements ...int64) Int64s {
	set := Int64s{
		backing: make(map[int64]struct{}),
	}
	for _, x := range initialElements {
		set.Add(x)
	}
	return set
}

func (set Int64s) Add(x int64) {
	set.backing[x] = struct{}{}
}

func (set Int64s) Remove(x int64) {
	delete(set.backing, x)
}

func (set Int64s) Contains(x int64) bool {
	_, ok := set.backing[x]
	return ok
}

func (set Int64s) Comprises(vals ...int64) bool {
	if set.Count() != len(vals) {
		return false
	}
	for _, v := range vals {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

func (set Int64s) Count() int {
	return len(set.backing)
}

func (set Int64s) Elements() []int64 {
	elm := make([]int64, 0, set.Count())
	for x, _ := range set.backing {
		elm = append(elm, x)
	}
	return elm
}

func (set Int64s) Clear() {
	for x, _ := range set.backing {
		set.Remove(x)
	}
}

func (set Int64s) Clone() Int64s {
	result := NewInt64s()
	for x, _ := range set.backing {
		result.Add(x)
	}
	return result
}

// ------------------------------------------------------------

func (a Int64s) Union(b Int64s) Int64s {
	result := a.Clone()
	for x, _ := range b.backing {
		result.Add(x)
	}
	return result
}

func (a Int64s) Intersection(b Int64s) Int64s {
	result := NewInt64s()

	smaller, larger := a, b
	if a.Count() > b.Count() {
		smaller, larger = b, a
	}

	for x, _ := range smaller.backing {
		if larger.Contains(x) {
			result.Add(x)
		}
	}
	return result
}

func (a Int64s) Difference(b Int64s) Int64s {
	result := a.Union(b)

	smaller, larger := a, b
	if a.Count() > b.Count() {
		smaller, larger = b, a
	}

	for x, _ := range smaller.backing {
		if larger.Contains(x) {
			result.Remove(x)
		}
	}
	return result
}

// Subtraction is non-commutative: a-b is different to b-a.
func (a Int64s) Subtract(b Int64s) Int64s {
	result := a.Clone()
	for x, _ := range b.backing {
		result.Remove(x)
	}
	return result
}
