// Code generated by github.com/frou/poor-mans-generics ; DO NOT EDIT.

package set

type Uint32s struct {
	backing map[uint32]struct{}
}

func NewUint32s(initialElements ...uint32) *Uint32s {
	set := new(Uint32s)
	for _, x := range initialElements {
		set.Add(x)
	}
	return set
}

func (set *Uint32s) Add(x uint32) {
	if set.backing == nil {
		set.backing = make(map[uint32]struct{})
	}
	set.backing[x] = struct{}{}
}

func (set *Uint32s) Remove(x uint32) {
	delete(set.backing, x)
}

func (set *Uint32s) Contains(x uint32) bool {
	_, ok := set.backing[x]
	return ok
}

func (set *Uint32s) Comprises(vals ...uint32) bool {
	if set.Count() != len(vals) {
		return false
	}
	for _, v := range vals {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

func (set *Uint32s) Count() int {
	return len(set.backing)
}

func (set *Uint32s) Elements() []uint32 {
	elm := make([]uint32, 0, set.Count())
	for x, _ := range set.backing {
		elm = append(elm, x)
	}
	return elm
}

func (set *Uint32s) Clear() {
	for x, _ := range set.backing {
		set.Remove(x)
	}
}

func (set *Uint32s) Clone() *Uint32s {
	result := NewUint32s()
	for x, _ := range set.backing {
		result.Add(x)
	}
	return result
}

// ------------------------------------------------------------

func (a *Uint32s) Union(b *Uint32s) *Uint32s {
	result := a.Clone()
	for x, _ := range b.backing {
		result.Add(x)
	}
	return result
}

func (a *Uint32s) Intersection(b *Uint32s) *Uint32s {
	result := NewUint32s()

	smaller, larger := a, b
	if a.Count() > b.Count() {
		smaller, larger = b, a
	}

	for x, _ := range smaller.backing {
		if larger.Contains(x) {
			result.Add(x)
		}
	}
	return result
}

func (a *Uint32s) Difference(b *Uint32s) *Uint32s {
	result := a.Union(b)

	smaller, larger := a, b
	if a.Count() > b.Count() {
		smaller, larger = b, a
	}

	for x, _ := range smaller.backing {
		if larger.Contains(x) {
			result.Remove(x)
		}
	}
	return result
}

// Subtraction is non-commutative: a-b is different to b-a.
func (a *Uint32s) Subtract(b *Uint32s) *Uint32s {
	result := a.Clone()
	for x, _ := range b.backing {
		result.Remove(x)
	}
	return result
}
